#pragma once

// Central definition of all AudioProcessorValueTreeState parameter IDs for
// Tenebrae. See docs/architecture.md for the corresponding signal-flow
// diagram.
//
// FROZEN AS OF THE v0.1 PARAMETER LAYOUT:
// Parameter IDs below must NEVER change once shipped - saved sessions and
// presets persist the APVTS state keyed by these string IDs, and renaming or
// removing one would silently break every user's saved state. Ranges,
// defaults, and skew MAY still be refined during voicing/tuning milestones;
// only the IDs themselves are frozen.
namespace ParamIDs
{
    // "Tight" high-pass pre-emphasis: strips low end before the cascade so
    // palm mutes stay tight/percussive instead of farting out into the
    // gain stages.
    inline constexpr auto tight = "tight";

    // Pre-gain into the oversampled 3-stage waveshaper cascade - the main
    // "how much distortion" control.
    inline constexpr auto gain = "gain";

    // Passive-style tone stack, applied after the cascade: shelving/peaking
    // bands modelled loosely on a guitar-amp tone stack.
    inline constexpr auto bass = "bass";
    inline constexpr auto mid = "mid";
    inline constexpr auto treble = "treble";

    // Output trim, applied after the tone stack and before the dry/wet mix.
    inline constexpr auto level = "level";

    // Dry/wet mix. At 0% the plugin is a delay-compensated passthrough of
    // the input (see TenebraeEngine's DryWetMixer usage).
    inline constexpr auto mix = "mix";

    // Cascade voicing: selects between two fixed sets of per-stage asymmetry
    // and interstage HP/LP corners (see TenebraeEngine.cpp) - "Tight" is the
    // v0.1 cascade, "Loose" is a softer-driven, wider-band alternative
    // voicing added in M1. Not a continuous control; changing it may produce
    // a small audible step, same as a physical amp channel-select switch.
    inline constexpr auto voicing = "voicing";

    // Bright: a fixed pre-cascade high-shelf pre-emphasis, modelled on the
    // "bright switch"/brighter-cab presence character of a high-gain amp
    // channel - not a full cab-sim (that is a convolution-based plugin
    // elsewhere in the suite). Off by default.
    inline constexpr auto bright = "bright";

    // Tone Voice: a fixed dB tilt added on top of the Bass/Mid/Treble bands
    // (Flat/Scoop/Boost - see ToneStack::setToneVoice), giving a one-switch
    // character shift while the individual band knobs remain fully live on
    // top of it.
    inline constexpr auto toneVoice = "toneVoice";

    // v0.2.0 additions (docs/design-brief.md) - added below the frozen v0.1
    // block above, per this file's own "IDs never change, more may be
    // added" contract.

    // Presence: a post-cascade, post-tone-stack high-shelf (fixed 2.4 kHz
    // corner - see docs/design-brief.md section 3.3), modelled on the
    // reference class's power-amp Presence feedback control's functional
    // position, not its circuit. 0 dB (unity) is a true passthrough - see
    // TenebraeEngine.cpp's bypass-at-default handling.
    inline constexpr auto presence = "presence";

    // Gate: a conventional fixed attack/hold/release expander/gate, inserted
    // after Presence and before Level (see docs/design-brief.md section
    // 3.5) - gates the fully-voiced wet signal, not the raw pre-cascade
    // input, so noise generated by the cascade's own gain is caught too.
    inline constexpr auto gateThreshold = "gateThreshold";
    inline constexpr auto gateAttack = "gateAttack";
    inline constexpr auto gateHold = "gateHold";
    inline constexpr auto gateRelease = "gateRelease";

    // Gate bypass. Default ON - a deliberate, explicitly-flagged default
    // change (see docs/design-brief.md section 5's honesty note): the
    // research is unanimous that a gate is a structural expectation of
    // "tight chug" tone in this genre, not an optional add-on.
    inline constexpr auto gateOn = "gateOn";

    // v0.3.0 additions - appended below the frozen v0.1/v0.2 blocks above,
    // per this file's own "IDs never change, more may be added" contract.
    //
    // Every one of these defaults to a NEUTRAL value, so a v0.2 session (which
    // contains none of them) loads with the Classic engine, the power amp off
    // and the gate at its legacy behaviour, and therefore renders exactly as
    // it did before. tests/StateTests.cpp (T-S1) is the release gate on that.

    // Engine: selects the whole tone-generating core. "Classic" is the
    // untouched v0.2 path (asymmetric-tanh cascade at 8x); "Triode" is the
    // v0.3.0 stateful triode-stage engine (see src/dsp/TriodeCascade.h).
    // Not automatable - it changes the reported latency.
    inline constexpr auto engine = "engine";

    // Quality: oversampling factor/filter family for the Triode engine only
    // (Eco 2x IIR / Standard 4x IIR / HQ 8x linear-phase FIR). Inert while
    // the Classic engine is selected, which keeps its own fixed 8x path.
    // Not automatable - it changes the reported latency.
    inline constexpr auto quality = "quality";

    // Bias Shift: scales all three triode stages' dynamic-bias depths, i.e.
    // how much blocking distortion / post-overload cutoff the cascade shows.
    // 100 % is the voicing's own calibrated depth.
    inline constexpr auto stageBias = "stageBias";

    // Power Amp: engages the negative-feedback power-amp block (output
    // transformer saturation + Resonance/Presence in the feedback return
    // path + supply sag). Off by default; when off the signal path is
    // structurally identical to v0.2's.
    inline constexpr auto powerAmp = "powerAmp";

    // Resonance: low-frequency feedback depth of the power-amp block - the
    // genre-defining low-end "depth" control. 0 dB is neutral.
    inline constexpr auto resonance = "resonance";

    // Sag: supply-sag depth, modulating the output transformer's headroom
    // from the output envelope. 0 % is neutral.
    inline constexpr auto sag = "sag";

    // Gate Key: where the gate's detector reads from - "Post" is the v0.2
    // behaviour (the gated signal itself), "Pre" taps a pre-distortion copy
    // of the plugin input through a fixed detector band-pass.
    inline constexpr auto gateKey = "gateKey";

    // Gate Hysteresis: the gap between the gate's open and close thresholds.
    // 0 dB collapses to v0.2's single threshold.
    inline constexpr auto gateHysteresis = "gateHysteresis";

    // Gate Range: the gate's closed-state floor in dB of attenuation. The
    // parameter's maximum position is "Mute" (a hard zero), which is the
    // v0.2 behaviour and the default.
    inline constexpr auto gateRange = "gateRange";

    // Gate Release Mode: "Manual" is v0.2's fixed one-pole release driven by
    // Gate Release; "Auto" is the program-dependent dual-envelope release.
    inline constexpr auto gateReleaseMode = "gateReleaseMode";
}
